apiVersion: v1
kind: Service
metadata:
  name: dns-test
spec:
  type: ClusterIP
  selector:
    rank: master
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dnsutils
  namespace: default
  labels:
    rank: master
spec:
  template:
    spec:
      containers:
        - name: dnsutils
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command:
            - sleep
            - "3600"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dnsutils2
  namespace: default
  labels:
    rank: worker
spec:
  template:
    spec:
      containers:
        - name: dnsutils
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command:
            - sleep
            - "3600"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
