apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-worker
  template:
    metadata:
      labels:
        app: test-worker
    spec:
      containers:
        - name: test-worker
          image: 9point/ml-project-news-classifier
          command: ["python", "./main.py", "start"]
          env:
            - name: API_ENDPOINT
              value: mlapiservice.default.svc.cluster.local:50051
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: primary.secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: primary.secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: IMAGE_NAME
              value: 9point/ml-project-news-classifier
            - name: LOCAL_CACHE_DIR
              value: /tmp/s3-cache
            - name: PROJECT_NAME
              value: news-classifier
            - name: SPACES_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: primary.configs
                  key: SPACES_BUCKET
            - name: SPACES_REGION
              valueFrom:
                configMapKeyRef:
                  name: primary.configs
                  key: SPACES_REGION
      restartPolicy: Always
